     The Substitute Galactic Exchange is run using the new Black Hole BBS
software on a Blue Chip PC compatible with 512K of memory, a Seagate 20 meg
hard drive, and a Discovery 1200H internal modem.  This bulletin board is
currently serving as a beta-test site for the Black Hole BBS software.
