     Welcome to the Black Hole BBS!  If you would like to become a member, then
please answer the following questions correctly.  I will call you sometime in
the next few days to verify your account and make you a member.
