     While on the Black Hole BBS, please observe the following rules of
conduct:

 1.  No calling other users nasty names.

 2.  No trading of k00l warez.

 3.  No smoking at the sysop's house, as this will result in his computer
turning yellow.

     Thanks for your support!
